// <auto-generated />
namespace Team9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Team92 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Team92));
        
        string IMigrationMetadata.Id
        {
            get { return "201611251606484_Team9.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
