// <auto-generated />
namespace Team9.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Team91 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Team91));
        
        string IMigrationMetadata.Id
        {
            get { return "201611241826196_Team9.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
